<?php

namespace AppBundle\Repository;

/**
 * BillDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
