<?php

namespace AppBundle\Repository;

/**
 * WasteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WasteTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
